services:
  # FinLLM API 서버
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finllm-api-server
    environment:
      DATABASE_URL: mysql+pymysql://alstpdusMin:Alstpdus!!@finance-db.c36egosuec87.ap-northeast-2.rds.amazonaws.com:3306/stock_data
      API_SERVER_URL: http://0.0.0.0:8000
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs