services:
  # FinLLM API 서버
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finllm-api-server
    environment:
      DATABASE_URL: postgresql://postgres:password@211.188.57.245:5432/finance_db
      API_SERVER_URL: http://0.0.0.0:8000
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs